version: 2.1
jobs:
  tests:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: ~/rnToDo
      - rn/yarn_install
      - run:
          command: yarn test
          name: Jest
orbs:
  react-native: react-native-community/react-native@3.0.1
workflows:
  version: 2
  todoapp:
    jobs:
      - tests